# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['run_app.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('.env', '.'),
        ('data', 'data'),
        ('document', 'document'),
        ('scripts', 'scripts'),
        ('staad_automation', 'staad_automation'),
        ('ui', 'ui'),
        ('assets', 'assets'),
        ('projects.json', '.'),
        ('reporte de staad _LA.docx', '.'),
        ('Límites de deflexión.xlsx', '.'),
        ('XtraReport.xlsx', '.'),
        ('Manual_de_Usuario.docx', '.')
    ],
    hiddenimports=[
        'flet',
        'flet.fastapi',
        'flet_core',
        'flet_runtime',
        'pythoncom',
        'pywintypes',
        'docx',
        'dotenv',
        'PIL.ImageGrab',
        'altgraph',
        'anyio',
        'arrow',
        'binaryornot',
        'Bottleneck',
        'certifi',
        'chardet',
        'charset_normalizer',
        'click',
        'colorama',
        'comtypes',
        'contourpy',
        'cookiecutter',
        'cycler',
        'et_xmlfile',
        'flet_cli',
        'flet_desktop',
        'fonttools',
        'h11',
        'httpcore',
        'httpx',
        'idna',
        'Jinja2',
        'kiwisolver',
        'lxml',
        'markdown_it_py',
        'MarkupSafe',
        'matplotlib',
        'mdurl',
        'numpy',
        'oauthlib',
        'openpyxl',
        'packaging',
        'pandas',
        'pefile',
        'pillow',
        'Pygments',
        'pyinstaller',
        'pyinstaller_hooks_contrib',
        'pyparsing',
        'pypng',
        'python_dateutil',
        'python_docx',
        'dotenv',
        'python_slugify',
        'pytz',
        'pywin32_ctypes',
        'PyYAML',
        'qrcode',
        'repath',
        'requests',
        'rich',
        'setuptools',
        'sip',
        'six',
        'sniffio',
        'text_unidecode',
        'toml',
        'tornado',
        'types_python_dateutil',
        'typing_extensions',
        'tzdata',
        'urllib3',
        'watchdog',
        'wheel',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='MemoriaDeCalculo',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='assets/icon.ico'
)
