IMAGE_SLOTS = {
    "isometrica3D":   (1, "Vista isométrica 3D …Nombre de la estructura…"),
    "isometricacondimensiones": (2, "Isometría con dimensiones …Nombre de la estructura…"),
    "nodos":          (3, "Vista numeración de nodos"),
    "vigas":          (4, "Vista numeración de vigas"),
    "perfiles":       (5, "Vista de perfiles"),
    "miembros_fisicos_continuos": (6, "Vista de miembros físicos continuos"),
    "mass":           (7, "Carga tipo mass"),
    "peso_propio":    (8,"Peso propio de la estructura (D)"),
    "operacion":      (9,"Carga de operación (Do)"),
    "hidrostatica":   (10,"Carga de prueba hidrostática (F)"),
    "viva":           (11,"Carga viva de la estructura (L)"),
    "termica":        (12,"Carga temperatura (TST)"),
    "friccion":       (13,"Fuerzas de fricción (TT)"),
    "anclaje":        (14,"Fuerzas de anclaje (TS)"),
    "viento_x":       (15,"Fuerzas de viento en dirección X (Wx)"),
    "viento_-x":      (16,"Fuerzas de viento en dirección -X (Wx)"),
    "viento_z":       (17,"Fuerzas de viento en dirección Z (Wz)"),
    "viento_-z":      (18,"Fuerzas de viento en dirección -Z (Wz)"),
    "despl_vertical": (19,"Viga con mayor desplazamiento vertical"),
    "despl_vertical": (20,"Viga con mayor desplazamiento horizontal"),
    "despl_viento_cols_v": (21,"Columnas con mayor desplazamiento horizontal X por carga de viento"),
    "despl_viento_cols_h":    (22,"Columnas con mayor desplazamiento horizontal Z por carga de viento"),
    "despl_sismo_cols_v": (23,"Columnas con mayor desplazamiento horizontal X por carga de sismo"),
    "despl_sismo_cols_v": (24,"Columnas con mayor desplazamiento horizontal Z por carga de sismo"),
    "ratio": (25,"Elemento con mayor ratio de diseño")
}